const { second } = require("./second");

it("Counts how many obstacles can be placed to create an infinite loop", () => {
  const textFile = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`;

  const loopObstacles = second(textFile);
  expect(loopObstacles).toBe(6);
});
